# Basic
title: zombie的博客
#subtitle: blogs for zombie
#welcome_message: <a href="https://github.com/zombiiee/zombiiee.github.io" target="_blank">Download the theme</a>
description: blogs for zombie.
author: zombie
#creator: <a href="http://onev.cat">@onevcat</a>

url: "http://zombiiee.com"

permalink: /:year/:month/:title/
#permalink: posts/:category/:title.html

# Format
#highlighter: rouge
## 代码块设置
highlight:
  enable: true
  line_number: true
  auto_detect: true #代码自动高亮
  tab_replace:

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: white

# The blog button should not be removed.
blog_button:
    title: Blog
    description: visit blog

# Navigation buttons in the front page.
#nav:
    #- {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: zombiiee
    # duoshuo:

# Social
social:
    weibo: zombiiee
    github: zombiiee
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail: duanchengwen07@163.com

# Google Analytics
#ga:
    # id: your_ga_id
    # host: your_host
